### ISSUE TITLE
ask for a question

### ISSUE THREAD

**Issue by Vinbert0203** [vandana-rajan/1D-Speech-Emotion-Recognition#1]
Hi, thanks for your share, it's very great!
i have a question:  for the function "train(model,x_tr,y_tr,x_val,y_val,args)" in cnn1d.py, you have written "return model",  here is it "return history"? thanks again

**Comment by vandana-rajan** [comment]
Hi,
I had previously used the 'history' to draw some plots. You can return and use it if you want to plot the loss or accuracy curves.

**Comment by Vinbert0203** [comment]
Thanks very much. I got it.
