### ISSUE TITLE
Use another dataset

### ISSUE THREAD

**Issue by ngragaei** [vandana-rajan/1D-Speech-Emotion-Recognition#2]
How to use my own dataset?

**Comment by vandana-rajan** [comment]
You have to write a data pre-processing script like the 'emodata1d.py' for your dataset and create numpy arrays with your training, validation and test data.

**Comment by ngragaei** [comment]
Thanks for your reply!
I used my dataset and it works. But if my classes names have two letters not one
instead of ['W','L','E','A','F','T','N'] --- ['LD','HD','CH,'TY']. what shall i change in order to load my data?

**Comment by vandana-rajan** [comment]
You should convert the class labels to one-hot vectors. Assign a number to each of the label. Refer the function string2num in the emodata1d.py. Also, change the number of classes from 7 to 4 at the last layer of the network.

**Comment by vandana-rajan** [comment]
Closing this issue for now. Please re-open if needed.
