### ISSUE TITLE
A few questions about the code

### ISSUE THREAD

**Issue by linxue123** [vandana-rajan/1D-Speech-Emotion-Recognition#3]
Hello, I have some questions to ask you. What is the final evaluation index?  What else besides val_categorical_accuracy?  In addition, how did the average precision cross data of emotions in Table 3 of the paper come from?  What is score = test(model,x_t,y_t),x_t,y_t?  thanks。

**Comment by vandana-rajan** [comment]
Hi,

Final evaluation index is currently categorical accuracy (7 class). Besides that you can may be check the loss value. If you are interested in a more detailed analysis, may be you can also check the embeddings of the last layer and check the distance between embeddings (within class and between class) or plot those embeddings.
In the paper, from what I understood, the average value they mentioned is taken by averaging the accuracy values obtained for each class (I am not exactly sure though, you might contact the authors.). score is ['loss', 'categorical_accuracy'].

**Comment by linxue123** [comment]
Thank you very much for your reply. I have one more question to ask you. I would like to know how to use the dataset IEMOCAP?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vandana-rajan/1D-Speech-Emotion-Recognition"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月28日(星期五) 晚上6:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vandana-rajan/1D-Speech-Emotion-Recognition] A few questions about the code (#3)





 
Hi,
 
Final evaluation index is currently categorical accuracy (7 class). Besides that you can may be check the loss value. If you are interested in a more detailed analysis, may be you can also check the embeddings of the last layer and check the distance between embeddings (within class and between class) or plot those embeddings.
 In the paper, from what I understood, the average value they mentioned is taken by averaging the accuracy values obtained for each class (I am not exactly sure though, you might contact the authors.). score is ['loss', 'categorical_accuracy'].
