### ISSUE TITLE
I took errors like this pls help!!!

### ISSUE THREAD

**Issue by Semakzl** [vandana-rajan/1D-Speech-Emotion-Recognition#4]
line 41, in data1d
    cname = int(dict.keys()[i])
TypeError: 'dict_keys' object is not subscriptable
And dont  know how to fix I'm searching the solutions but i haven't found if you know anything about my issues pls help  me bcs your work help me a lot to do my own project.

**Comment by vandana-rajan** [comment]
Hi,

The error looks like a Python version mismatch. This code is based on Python 2.7. I suspect you might be using Python 3!
The solution in the link below might be able to help.

https://stackoverflow.com/questions/26394748/nltk-python-error-typeerror-dict-keys-object-is-not-subscriptable

**Comment by Semakzl** [comment]
Thank you very much to answer my question that quick. I'm so thankful for you.
